/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.NuevoClienteController;
import Model.Conexion;
import Model.NuevoClienteModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JTable;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author kewin
 */
public class GestionarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionarCliente
     */
    
    private int idClientes;
    
    public GestionarCliente() {
        initComponents();
        this.setSize(800, 630);
        this.setTitle("Gestionar Clientes");
        this.CargarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        Bt_Actualizar = new javax.swing.JButton();
        Bt_Eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_CUI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_APELLIDO = new javax.swing.JTextField();
        txt_NOMBRE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_TELEFONO = new javax.swing.JTextField();
        txt_DIRECCION = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestion De Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Bt_Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bt_Actualizar.setText("Actualizar");
        Bt_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ActualizarActionPerformed(evt);
            }
        });

        Bt_Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bt_Eliminar.setText("Eliminar");
        Bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_EliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CUI");

        txt_CUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CUIActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("APELLIDO");

        txt_APELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_APELLIDOActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TELEFONO");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("DIRECCION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bt_Actualizar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_CUI, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(Bt_Eliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_TELEFONO)
                                            .addComponent(txt_DIRECCION))))))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Actualizar)
                    .addComponent(Bt_Eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_CUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CUIActionPerformed

    private void txt_APELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_APELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_APELLIDOActionPerformed

    private void Bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_EliminarActionPerformed
        // TODO add your handling code here:
        NuevoClienteController cliente = new NuevoClienteController();
        if(idClientes == 0){
            JOptionPane.showMessageDialog(null, "Seleccione un cliente!");
            
        }else{
            if(cliente.eliminar(idClientes)){
               JOptionPane.showMessageDialog(null, "Cliente Eliminado!");
               this.CargarTablaClientes();
               this.Limpiar();
            }else{
               JOptionPane.showMessageDialog(null, "Seleccione un cliente!");
            }
        }
    }//GEN-LAST:event_Bt_EliminarActionPerformed

    private void Bt_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ActualizarActionPerformed
        // TODO add your handling code here:
        if(!txt_CUI.getText().isEmpty() || !txt_NOMBRE.getText().isEmpty() || !txt_APELLIDO.getText().isEmpty() || !txt_TELEFONO.getText().isEmpty() || !txt_DIRECCION.getText().isEmpty()){
            NuevoClienteModel clienteModel = new NuevoClienteModel();
            NuevoClienteController clienteController = new NuevoClienteController();
            
            if(clienteController.actualizarCliente(clienteModel, idClientes)){
                JOptionPane.showMessageDialog(null, "Registro Actualizado!");
                this.CargarTablaClientes();
                this.Limpiar();
            }else{
                 JOptionPane.showMessageDialog(null, "Error al actualizar!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un cliente!");
        }
    }//GEN-LAST:event_Bt_ActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Actualizar;
    private javax.swing.JButton Bt_Eliminar;
    public static javax.swing.JTable TablaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_APELLIDO;
    private javax.swing.JTextField txt_CUI;
    private javax.swing.JTextField txt_DIRECCION;
    private javax.swing.JTextField txt_NOMBRE;
    private javax.swing.JTextField txt_TELEFONO;
    // End of variables declaration//GEN-END:variables
    
    private void enviarDatosClienteSeleccionado(int idCliente){
        try {
            Connection conec = Conexion.conectarDB();
            PreparedStatement pst = conec.prepareStatement("SELECT * FROM Cliente WHERE ID_Cliente = '"+ idCliente + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()) {
                txt_CUI.setText(rs.getString("CUI"));
                txt_NOMBRE.setText(rs.getString("NOMBRE"));
                txt_APELLIDO.setText(rs.getString("APELLIDO"));
                txt_TELEFONO.setText(rs.getString("TELEFONO"));
                txt_DIRECCION.setText(rs.getString("DIRECCION"));
            }
            
        } catch (Exception e) {
        }
    }
    

    private void CargarTablaClientes(){
        Connection conec = Conexion.conectarDB();
        DefaultTableModel tableModel = new DefaultTableModel();
        String sql = "SELECT ID_Cliente, CUI, NOMBRE, APELLIDO, TELEFONO, DIRECCION FROM Cliente";
        Statement st;
        
        try {
            st = conec.createStatement();
            ResultSet rs = st.executeQuery(sql);
            GestionarCliente.TablaClientes = new JTable(tableModel);
            GestionarCliente.jScrollPane1.setViewportView(GestionarCliente.TablaClientes);
            
            tableModel.addColumn("ID");
            tableModel.addColumn("CUI");
            tableModel.addColumn("NOMBRE");
            tableModel.addColumn("APELLIDO");
            tableModel.addColumn("TELEFONO");
            tableModel.addColumn("DIRECCION");
            
            while(rs.next()){
                Object fila[] = new Object[6];
                
                for(int i=0; i < 6; i++){
                    fila[i] = rs.getObject(i + 1);
                }
                tableModel.addRow(fila);
                
            }
            
            conec.close();
            
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla clientes: " + e);
        }
        
        
        TablaClientes.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = TablaClientes.rowAtPoint(e.getPoint());
                int columna_point = 0;
                
                if(fila_point > -1 ) {
                    idClientes = (int) tableModel.getValueAt(fila_point, columna_point);
                    enviarDatosClienteSeleccionado(idClientes);
                } 
                
            }
        });
    }
    
    private void Limpiar(){
        txt_CUI.setText("");
        txt_NOMBRE.setText("");
        txt_APELLIDO.setText("");
        txt_TELEFONO.setText("");
        txt_DIRECCION.setText("");
    }

}

