/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author kewin
 */
public class LibrosView extends javax.swing.JFrame {

    /**
     * Creates new form LibrosView
     */
    public LibrosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTNombreL = new javax.swing.JTextField();
        TXTAutorL = new javax.swing.JTextField();
        TXTFechaL = new javax.swing.JTextField();
        BTRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TXTCopias = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTEditorialL = new javax.swing.JTextArea();
        BTGuardarLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("LIBROS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setText("NO. DE COPIAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setText("AUTOR(A)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setText("FECHA DE LANZAMIENTO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));
        getContentPane().add(TXTNombreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 92, 470, 20));

        TXTAutorL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTAutorLActionPerformed(evt);
            }
        });
        getContentPane().add(TXTAutorL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 470, 20));

        TXTFechaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFechaLActionPerformed(evt);
            }
        });
        getContentPane().add(TXTFechaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 470, 20));

        BTRegresar.setText("REGRESAR");
        BTRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BTRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel6.setText("EDITORIAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        TXTCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCopiasActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 20));

        TXTEditorialL.setColumns(20);
        TXTEditorialL.setRows(5);
        jScrollPane1.setViewportView(TXTEditorialL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 470, 70));

        BTGuardarLibro.setText("GUARDAR");
        BTGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGuardarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(BTGuardarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTAutorLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTAutorLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTAutorLActionPerformed

    private void TXTFechaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFechaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFechaLActionPerformed

    private void TXTCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCopiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCopiasActionPerformed

    private void BTRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menuPrincipal = new MenuPrincipal();
        menuPrincipal.setVisible(true);
        menuPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_BTRegresarActionPerformed

    private void BTGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGuardarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTGuardarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTGuardarLibro;
    public javax.swing.JButton BTRegresar;
    public javax.swing.JTextField TXTAutorL;
    public javax.swing.JTextField TXTCopias;
    public javax.swing.JTextArea TXTEditorialL;
    public javax.swing.JTextField TXTFechaL;
    public javax.swing.JTextField TXTNombreL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
