/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author kewin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    public static JDesktopPane jDesktopPane_menu;
    
    
    public Menu() {
        initComponents();
        this.setSize(new Dimension(1000,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema Bancario");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto -110));
        this.add(jDesktopPane_menu);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        NuevoUsuario = new javax.swing.JMenuItem();
        ActualizarUsuario = new javax.swing.JMenuItem();
        VisualizarUsuario = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        NuevoCliente = new javax.swing.JMenuItem();
        GestionarCliente = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        NuevaCuenta = new javax.swing.JMenuItem();
        EliminarCuenta = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        VisualizarDepositos = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        VisualizarTransferencias = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        PagosServicios = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu12.setText("File");
        jMenuBar5.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar5.add(jMenu13);

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem17.setText("jMenuItem17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu7.setText("Usuario");
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        NuevoUsuario.setText("Nuevo Usuario");
        NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu7.add(NuevoUsuario);

        ActualizarUsuario.setText("Actualizar Usuario");
        jMenu7.add(ActualizarUsuario);

        VisualizarUsuario.setText("Visualizar Usuarios");
        VisualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarUsuarioActionPerformed(evt);
            }
        });
        jMenu7.add(VisualizarUsuario);

        jMenuBar4.add(jMenu7);

        jMenu8.setText("Cliente");
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        NuevoCliente.setText("Nuevo Cliente");
        NuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoClienteActionPerformed(evt);
            }
        });
        jMenu8.add(NuevoCliente);

        GestionarCliente.setText("Gestionar Cliente");
        GestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarClienteActionPerformed(evt);
            }
        });
        jMenu8.add(GestionarCliente);

        jMenuBar4.add(jMenu8);

        jMenu9.setText("Cuenta");
        jMenu9.setPreferredSize(new java.awt.Dimension(150, 50));

        NuevaCuenta.setText("Nueva Cuenta");
        jMenu9.add(NuevaCuenta);

        EliminarCuenta.setText("Eliminar Cuenta");
        jMenu9.add(EliminarCuenta);

        jMenuBar4.add(jMenu9);

        jMenu10.setText("Deposito");
        jMenu10.setPreferredSize(new java.awt.Dimension(150, 50));

        VisualizarDepositos.setText("Visualizar Depositos");
        jMenu10.add(VisualizarDepositos);

        jMenuBar4.add(jMenu10);

        jMenu11.setText("Transferencia");
        jMenu11.setPreferredSize(new java.awt.Dimension(150, 50));

        VisualizarTransferencias.setText("Visualizar Transferencias");
        jMenu11.add(VisualizarTransferencias);

        jMenuBar4.add(jMenu11);

        jMenu14.setText("Pago De Servicios");
        jMenu14.setPreferredSize(new java.awt.Dimension(150, 50));

        PagosServicios.setText("Visualizar Pagos");
        jMenu14.add(PagosServicios);

        jMenuBar4.add(jMenu14);

        jMenu15.setText("Salir");
        jMenu15.setPreferredSize(new java.awt.Dimension(100, 50));
        jMenuBar4.add(jMenu15);

        setJMenuBar(jMenuBar4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizarUsuarioActionPerformed

    private void GestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarClienteActionPerformed
        // TODO add your handling code here:
        GestionarCliente gestionCliente = new GestionarCliente();
        jDesktopPane_menu.add(gestionCliente);
        gestionCliente.setVisible(true);
        
    }//GEN-LAST:event_GestionarClienteActionPerformed

    private void NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoUsuarioActionPerformed

    private void NuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoClienteActionPerformed
        // TODO add your handling code here:
        NuevoCliente nuevoCliente = new NuevoCliente();
        jDesktopPane_menu.add(nuevoCliente);
        nuevoCliente.setVisible(true);
    }//GEN-LAST:event_NuevoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarUsuario;
    private javax.swing.JMenuItem EliminarCuenta;
    private javax.swing.JMenuItem GestionarCliente;
    private javax.swing.JMenuItem NuevaCuenta;
    private javax.swing.JMenuItem NuevoCliente;
    private javax.swing.JMenuItem NuevoUsuario;
    private javax.swing.JMenuItem PagosServicios;
    private javax.swing.JMenuItem VisualizarDepositos;
    private javax.swing.JMenuItem VisualizarTransferencias;
    private javax.swing.JMenuItem VisualizarUsuario;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
