/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.NuevoClienteController;
import Model.NuevoClienteModel;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author kewin
 */
public class NuevoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        this.setSize(new Dimension(600,400));
        this.setTitle("Nuevo Cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CUI = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Bt_Guardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DIRECCION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("CUI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NOMBRE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("APELLIDO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("TELEFONO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(CUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 370, -1));
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 260, -1));
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 540, -1));
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, -1));
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, -1));

        Bt_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bt_Guardar.setText("GUARDAR");
        Bt_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_GuardarActionPerformed
        // TODO add your handling code here:
        NuevoClienteModel nuevoClienteModel = new NuevoClienteModel();
        NuevoClienteController cliente = new NuevoClienteController(); 
        
        if(CUI.getText().isEmpty() || Nombre.getText().isEmpty() || Apellido.getText().isEmpty() || Telefono.getText().isEmpty() || Direccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todo los campos!");
        }else{
            
            if(!cliente.existeCliente(Integer.parseInt(CUI.getText().trim()))) {
               nuevoClienteModel.setCui(Integer.parseInt(CUI.getText()));
               nuevoClienteModel.setNombre(Nombre.getText().trim());
               nuevoClienteModel.setApellido(Apellido.getText().trim());
               nuevoClienteModel.setTelefono(Integer.parseInt(Telefono.getText().trim()));
               nuevoClienteModel.setDireccion(Direccion.getText().trim());
            if (cliente.nuevoCliente(nuevoClienteModel)) {
                JOptionPane.showMessageDialog(null, "Cliente guardado correctamente!");
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar cliente!");
            }
            }else{
               JOptionPane.showMessageDialog(null, "Cliente ya existe en la base de datos!");
            }

        }
        
        CUI.setText("");
        Nombre.setText("");
        Apellido.setText("");
        Telefono.setText("");
        Direccion.setText("");

    }//GEN-LAST:event_Bt_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JButton Bt_Guardar;
    private javax.swing.JTextField CUI;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
