/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kewin
 */
public class Visualizar extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarUsers
     */
    public Visualizar() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btUsuarios = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tableUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 400, 290));

        btUsuarios.setText("Productos");
        btUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        btEditar.setText("Editar Producto");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        btEliminar.setText("Eliminar Producto");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        btRegresar.setText("REGRESAR");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            String url = "http://localhost:4000/user";
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");
            con.setRequestProperty("Accept", "application/json");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            // Imprimir el JSON recibido
            String jsonResponse = response.toString();
            System.out.println("JSON Response: " + jsonResponse);

            // Remover corchetes si están presentes
            if (jsonResponse.startsWith("[") && jsonResponse.endsWith("]")) {
                jsonResponse = jsonResponse.substring(1, jsonResponse.length() - 1);  // Remueve corchetes []
            }

            // Dividir en objetos JSON individuales
            String[] users = jsonResponse.split("\\},\\{");

            DefaultTableModel model = (DefaultTableModel) tableUsuarios.getModel();
            model.setRowCount(0);  // Limpiar filas anteriores

            // Procesar cada usuario
            for (String user : users) {
                user = user.replace("{", "").replace("}", "");  // Remover las llaves
                String[] fields = user.split(",");

                Long id = null;
                String name = null;
                String descripcion = null;
                String precio = null;

                // Procesar cada campo del usuario
                for (String field : fields) {
                    String[] keyValue = field.split(":");
                    String key = keyValue[0].replace("\"", "").trim();
                    String value = keyValue[1].replace("\"", "").trim();

                    switch (key) {
                        case "id":
                            id = Long.parseLong(value);
                            break;
                        case "name":
                            name = value;
                            break;
                        case "description":
                            descripcion = value;
                            break;
                        case "precio":
                            precio = value;
                            break;
                    }
                }

                // Si todos los valores son válidos, añadir una nueva fila
                if (id != null && name != null && descripcion != null && precio != null) {
                    model.addRow(new Object[]{id, name, descripcion, precio});
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btUsuariosActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableUsuarios.getSelectedRow();

        if (selectedRow != -1) {  // Asegúrate de que se selecciona una fila
            Long userId = (Long) tableUsuarios.getValueAt(selectedRow, 0);  // Obtener ID del usuario seleccionado

            try {
                String url = "http://localhost:4000/user/" + userId;
                URL obj = new URL(url);
                HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                con.setRequestMethod("DELETE");

                int responseCode = con.getResponseCode();
                if (responseCode == HttpURLConnection.HTTP_OK) {
                    // Si el usuario fue eliminado correctamente
                    DefaultTableModel model = (DefaultTableModel) tableUsuarios.getModel();
                    model.removeRow(selectedRow);  // Remover la fila de la tabla
                    System.out.println("Producto eliminado");
                } else {
                    System.out.println("Error: No se pudo eliminar el Producto");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("Por favor selecciona un Producto para eliminar.");
        }
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        int selectedRow = tableUsuarios.getSelectedRow();

        if (selectedRow != -1) {  // Asegúrate de que se ha seleccionado una fila
            Long userId = (Long) tableUsuarios.getValueAt(selectedRow, 0);  // Obtener el ID del usuario seleccionado
            String newName = (String) tableUsuarios.getValueAt(selectedRow, 1);
            String newDescripcion = (String) tableUsuarios.getValueAt(selectedRow, 2);
            String newPrecio = (String) tableUsuarios.getValueAt(selectedRow, 3);

            try {
                String url = "http://localhost:4000/user/" + userId;
                URL obj = new URL(url);
                HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                // Configurar la solicitud PUT
                con.setRequestMethod("PUT");
                con.setRequestProperty("Content-Type", "application/json; utf-8");
                con.setRequestProperty("Accept", "application/json");
                con.setDoOutput(true);

                // Crear el JSON manualmente para enviar los datos actualizados del usuario
                String jsonInputString = "{";
                jsonInputString += "\"name\": \"" + newName + "\",";
                jsonInputString += "\"description\": \"" + newDescripcion + "\",";
                jsonInputString += "\"precio\": \"" + newPrecio + "\"";
                jsonInputString += "}";

                // Enviar el JSON en la solicitud
                try ( OutputStream os = con.getOutputStream()) {
                    byte[] input = jsonInputString.getBytes("utf-8");
                    os.write(input, 0, input.length);
                }

                int responseCode = con.getResponseCode();
                if (responseCode == HttpURLConnection.HTTP_OK) {
                    System.out.println("Producto actualizado correctamente");
                } else {
                    System.out.println("Error: No se pudo actualizar el producto en la base de datos");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("Por favor selecciona un producto para editar.");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_btRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableUsuarios;
    // End of variables declaration//GEN-END:variables
}
