/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LibroController;
import Controller.UsuarioController;
import Model.LibroModelDAO;
import Model.UsuarioModelDAO;

/**
 *
 * @author kewin
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTLibro = new javax.swing.JButton();
        BTAsignar = new javax.swing.JButton();
        BTUsuario = new javax.swing.JButton();
        BTSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(502, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENU BIBLIOTECA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 15, -1, -1));

        BTLibro.setText("REGISTRAR LIBRO");
        BTLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLibroActionPerformed(evt);
            }
        });
        getContentPane().add(BTLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, 30));

        BTAsignar.setText("ASIGNAR LIBRO");
        BTAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAsignarActionPerformed(evt);
            }
        });
        getContentPane().add(BTAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, 30));

        BTUsuario.setText("REGISTRAR USUARIO");
        BTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, 30));

        BTSalir.setText("SALIR  DEL SISTEMA");
        BTSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BTSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLibroActionPerformed
        // TODO add your handling code here:
        LibrosView libroView = new LibrosView();
        LibroModelDAO libroModel = new LibroModelDAO();
        LibroController libroController = new LibroController(libroView, libroModel);

        libroView.setVisible(true);
        libroView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTLibroActionPerformed

    private void BTAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTAsignarActionPerformed

    private void BTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioView usuarioView = new UsuarioView();
        UsuarioModelDAO usuarioModel = new UsuarioModelDAO();
        UsuarioController usuarioController = new UsuarioController(usuarioView, usuarioModel);
        
        usuarioView.setVisible(true);
        usuarioView.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BTUsuarioActionPerformed

    private void BTSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalirActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_BTSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAsignar;
    private javax.swing.JButton BTLibro;
    private javax.swing.JButton BTSalir;
    private javax.swing.JButton BTUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
