/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraservicioweb;

import javax.swing.JOptionPane;

/**
 *
 * @author kewin
 */
public class APICalculadora extends javax.swing.JFrame {

    /**
     * Creates new form APICalculadora
     */
    public APICalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumeroUno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NumeroDos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        BTSumar = new javax.swing.JButton();
        BTRestar = new javax.swing.JButton();
        BTDividir = new javax.swing.JButton();
        BTMultiplicar = new javax.swing.JButton();
        BTLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CALCULADORA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 16, 90, 20));

        jLabel2.setText("NUMERO UNO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        NumeroUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroUnoActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, -1));

        jLabel3.setText("NUMERO DOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(NumeroDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 220, -1));

        jLabel4.setText("RESULTADO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 220, -1));

        BTSumar.setText("SUMAR");
        BTSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSumarActionPerformed(evt);
            }
        });
        getContentPane().add(BTSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        BTRestar.setText("RESTAR");
        BTRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRestarActionPerformed(evt);
            }
        });
        getContentPane().add(BTRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        BTDividir.setText("DIVIDIR");
        BTDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTDividirActionPerformed(evt);
            }
        });
        getContentPane().add(BTDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        BTMultiplicar.setText("MULTILPLICAR");
        BTMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(BTMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        BTLimpiar.setText("LIMPIAR");
        BTLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(BTLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSumarActionPerformed
        // TODO add your handling code here:
        try {
            int numeroUno = Integer.parseInt(NumeroUno.getText());
            int numeroDos = Integer.parseInt(NumeroDos.getText());
            CalculadoraServicioWeb client = new CalculadoraServicioWeb();
            String resultado = client.sumar(numeroUno, numeroDos);
            Resultado.setText(resultado);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_BTSumarActionPerformed

    private void NumeroUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroUnoActionPerformed

    private void BTDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTDividirActionPerformed
        // TODO add your handling code here:
        try {
            int numeroUno = Integer.parseInt(NumeroUno.getText());
            int numeroDos = Integer.parseInt(NumeroDos.getText());
            CalculadoraServicioWeb client = new CalculadoraServicioWeb();
            String resultado = client.dividir(numeroUno, numeroDos);
            Resultado.setText(resultado);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_BTDividirActionPerformed

    private void BTMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMultiplicarActionPerformed
        // TODO add your handling code here:
        try {
            int numeroUno = Integer.parseInt(NumeroUno.getText());
            int numeroDos = Integer.parseInt(NumeroDos.getText());
            CalculadoraServicioWeb client = new CalculadoraServicioWeb();
            String resultado = client.multiplicar(numeroUno, numeroDos);
            Resultado.setText(resultado);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_BTMultiplicarActionPerformed

    private void BTRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRestarActionPerformed
        // TODO add your handling code here:
        try {
            int numeroUno = Integer.parseInt(NumeroUno.getText());
            int numeroDos = Integer.parseInt(NumeroDos.getText());
            CalculadoraServicioWeb client = new CalculadoraServicioWeb();
            String resultado = client.restar(numeroUno, numeroDos);
            Resultado.setText(resultado);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_BTRestarActionPerformed

    private void BTLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimpiarActionPerformed
        // TODO add your handling code here:
        NumeroUno.setText("");
        NumeroDos.setText("");
        Resultado.setText("");
    }//GEN-LAST:event_BTLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APICalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTDividir;
    private javax.swing.JButton BTLimpiar;
    private javax.swing.JButton BTMultiplicar;
    private javax.swing.JButton BTRestar;
    private javax.swing.JButton BTSumar;
    private javax.swing.JTextField NumeroDos;
    private javax.swing.JTextField NumeroUno;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
